name: her2-class
channels:
  - conda-forge
  - nvidia
  - rapidsai-nightly
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=py312h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312hee96239_0
  - asttokens=3.0.0=py312h06a4308_0
  - async-lru=2.0.5=py312h06a4308_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.13.5=py312h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312h06a4308_0
  - bottleneck=1.4.2=py312ha883a20_0
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.10.5=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.0=pyh707e725_0
  - cmake=4.1.2=hc946e07_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cucim=25.12.00a22=cuda13_py312_251101_ghge7cc0c3_gn22}_phc494990
  - cuda-cccl_linux-64=13.0.85=ha770c72_0
  - cuda-cudart=13.0.96=hecca717_0
  - cuda-cudart-dev_linux-64=13.0.96=h376f20c_0
  - cuda-cudart-static_linux-64=13.0.96=h376f20c_0
  - cuda-cudart_linux-64=13.0.96=h376f20c_0
  - cuda-nvrtc=13.0.88=hecca717_0
  - cuda-version=13.0=hc7b4dd1_3
  - cupy=13.6.0=py312h045ee1a_2
  - cupy-core=13.6.0=py312h1a70bb2_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.16=py312hbdd6827_0
  - decorator=5.2.1=py312h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - elfutils=0.191=h924a536_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - eval_type_backport=0.2.2=pyha770c72_0
  - executing=2.2.1=py312h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - fastrlock=0.8.3=py312h8285ef7_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.10=h829c605_4
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.9=h86084c0_1
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.74.1=py312h6f3464c_1
  - gst-plugins-base=1.22.9=h8e1006c_0
  - gstreamer=1.22.9=h98fc4e7_0
  - h11=0.16.0=py312h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - httpcore=1.0.9=py312h06a4308_0
  - httpx=0.28.1=py312h06a4308_1
  - icu=73.2=h59595ed_0
  - idna=3.7=py312h06a4308_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.30.1=py312h06a4308_0
  - ipython=9.5.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - ipywidgets=8.1.7=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.2=py312h06a4308_0
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.2.5=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.8.1=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.16.0=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyterlab=4.4.7=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.15=py312h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.7=hadbb8c3_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=1.1.1=h5eee18b_0
  - libcap=2.71=h39aace5_0
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=13.1.0.3=h676940d_0
  - libcucim=25.12.00a22=cuda13_251101_ghge7cc0c3_gn22}_phc494990
  - libcufft=12.0.0.61=hecca717_0
  - libcufile=1.15.0.42=h88a938c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.4.0.35=h676940d_1
  - libcurl=8.15.0=hc1efc7f_0
  - libcusolver=12.0.4.66=h676940d_1
  - libcusparse=12.6.3.3=hecca717_0
  - libdeflate=1.20=hd590300_0
  - libdicom=1.0.5=hd590300_1
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=15.2.0=h767d61c_6
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.74.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libllvm18=18.1.8=default_hddf928d_9
  - libmicrohttpd=1.0.2=hc2fc477_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=13.0.88=hecca717_0
  - libnvjpeg=13.0.1.86=hecca717_0
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_0
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h753d276_0
  - libpq=16.10=h1cdf469_2
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=15.2.0=h4852527_6
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp=1.3.2=h658648e_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markdown=3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib=3.10.6=py312h06a4308_0
  - matplotlib-base=3.10.6=py312h71dd3da_0
  - matplotlib-inline=0.1.7=py312h06a4308_0
  - mesalib=24.1.0=hfa94a56_0
  - mistune=3.1.2=py312h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py312hacdc0fc_0
  - mkl_fft=1.3.11=py312hacdc0fc_1
  - mkl_random=1.2.8=py312h2fd27a0_1
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert=7.16.6=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbconvert-pandoc=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nettle=3.10.1=h4a9d5aa_0
  - networkx=3.5=pyhe01879c_0
  - ninja=1.13.1=h171cf75_0
  - notebook=7.4.5=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numexpr=2.11.0=py312h397f862_1
  - numpy=2.3.3=py312h3f4ed14_1
  - numpy-base=2.3.3=py312h6ab9638_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.10=he9288cc_1
  - openpyxl=3.1.5=py312h7f6eeab_2
  - openslide=4.0.0=h58ba908_1
  - openslide-python=1.4.2=py312h113609a_2
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.4.0=py312h06a4308_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=py312h06a4308_1
  - pandas=2.3.3=py312h505adc9_0
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py312h06a4308_0
  - parso=0.8.4=py312h06a4308_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py312h06a4308_0
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py312h06a4308_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.52=py312h06a4308_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - protobuf=6.31.1=py312hb8af0ac_2
  - psutil=7.0.0=py312hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.3=py312h06a4308_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.23=py312h06a4308_0
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py312h868fb18_0
  - pygments=2.19.1=py312h06a4308_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pyqt6-sip=13.10.2=py312hee96239_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=1_cp312
  - pytz=2025.2=py312h06a4308_0
  - pywavelets=1.9.0=py312h4f23490_1
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=27.1.0=py312hcf8288c_0
  - qt-main=5.15.8=h450f30e_18
  - qtconsole=5.7.0=py312h06a4308_0
  - qtpy=2.4.3=py312h06a4308_0
  - rdma-core=58.0=h7934f7d_0
  - re2=2025.08.12=h5301d42_1
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.5=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rhash=1.4.6=ha914fed_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - scikit-image=0.24.0=py312hf9745cd_3
  - scikit-learn=1.7.2=py312h505adc9_0
  - scipy=1.16.2=py312h36961ab_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py312h06a4308_1
  - sentry-sdk=2.43.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py312h66e93f0_0
  - setuptools=80.9.0=py312h06a4308_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.17.0=py312h06a4308_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py312h06a4308_0
  - statsmodels=0.14.5=py312h4f23490_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py312hee9fe19_3
  - terminado=0.18.1=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tifffile=2025.10.4=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py312h06a4308_0
  - wandb=0.22.3=py312h0ccc70a_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.13=py312h06a4308_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=4.0.14=py312h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-cursor=0.1.4=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-glproto=1.4.17=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - cachetools==6.2.1
      - cheroot==11.0.0
      - cucim-cu13==25.10.0
      - etils==1.13.0
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gcsfs==2025.10.0
      - google-api-core==2.28.1
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.4.1
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.71.0
      - gviz-api==1.10.0
      - importlib-resources==6.5.2
      - jaraco-functools==4.3.0
      - mako==1.3.10
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - oauthlib==3.3.1
      - propcache==0.4.1
      - proto-plus==1.26.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycuda==2025.1.2
      - pytools==2025.2.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - siphash24==1.8
      - sympy==1.14.0
      - tensorboard-plugin-profile==2.20.9
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
      - triton==3.5.0
      - xprof==2.20.9
      - yarl==1.22.0
prefix: /home/thanakornbuath/anaconda3/envs/her2-class
